name: Check Files Changed

on:
  workflow_call:
    inputs:
      files:
        type: string
        required: false

    outputs:
      any_changed:
        description: "Return true only when any files provided using the files input have changed."
        value: ${{ jobs.check_files_changed.outputs.any_changed }}

jobs:
  check_files_changed:
    name: Check Files Changed
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'atb-ventures' }}
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # OR "2" -> To retrieve the preceding commit.

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v19
        with:
          files: ${{ inputs.files }}

      - name: Echo
        run: echo "Any Changed ?? ${{ steps.changed-files.outputs.any_changed }}"
