name: "Image and Tag Exist"

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image to look for"
        type: string
        required: true

      tag:
        description: "Docker tag to look for"
        type: string
        required: true

      allow_tag_latest:
        description: "Do you want to let latest be approved?"
        type: boolean
        required: false
        default: false

jobs:
  image_tag_exists:
    name: Check Image and Tag Exist
    runs-on: [self-hosted]
    env:
      IMAGE: ${{ inputs.image }}
      TAG: ${{ inputs.tag }}
      ALLOW_LATEST_TAG: ${{ inputs.allow_tag_latest }}
    steps:
      - name: "Confirm Tag is or isn't LATEST"
        run: ./scripts/check-tag.sh
        shell: bash

      - run: |
          docker manifest inspect $IMAGE:$TAG > /dev/null ; echo $?

      - run: |
          echo "Image $IMAGE with tag $TAG exists!"
